### ISSUE TITLE
Change container image repository

### ISSUE THREAD

**Issue by devang-gaur** [fabric8-hdd/supervisor#24] opened 2017-12-07 09:39 UTC
https://github.com/fabric8-hdd/supervisor/blob/0acb50e25972b9be437de787f881b87f236825e8/Makefile#L1

We also need to make corresponding changes in the Dockerfiles

**Comment by anmolbabu** [comment] 2017-12-07 09:46
Closed duplicate of https://github.com/fabric8-hdd/supervisor/issues/2

**Closed as completed by anmolbabu** 2017-12-07 09:46 UTC

**Comment by devang-gaur** [comment] 2017-12-07 09:49
oh
